version: 1

# before:
#   hooks:
#     # You may remove this if you don't use go modules.
#     - go mod tidy

builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      # - arm64
    ldflags:
      - -s -w
      - "-X main.Version={{ .Version }}"
      - "-X main.Commit={{ .Commit }}"
      - "-X main.CommitDate={{ .CommitDate }}"
      - "-X main.TreeState={{ .GitTreeState }}"

archives:
  - format: binary
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: "{{ .ProjectName }}_{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

sboms:
  - artifacts: binary

# we are not signing here as this would use a GPG key from the REPO
# instead this will be signed by the slsa git generator using Sigstore's keyless signing
# signs:
#   - artifacts: all

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
