# This workflow runs test against the Go project

name: Go Test

on:
  push:
    branches:
      - main
      - feat*
    paths:
      - .github/workflows/go-test.yaml
      - pkg/**
      - cmd/**
      - go.*
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - pkg/**
      - cmd/**
      - go.*
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.3
      - run: go test -v -race ./...
