name: release-and-sbom
on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `0.8.4` or else

# Declare default deny permissions
permissions: {}

jobs:
  # 1st JOB: Generate ldflags dynamically.
  # Optional: only needed for ldflags.
  args:
    runs-on: ubuntu-latest
    outputs:
      commit-date: ${{ steps.ldflags.outputs.commit-date }}
      commit: ${{ steps.ldflags.outputs.commit }}
      version: ${{ steps.ldflags.outputs.version }}
      tree-state: ${{ steps.ldflags.outputs.tree-state }}
      tag: ${{ steps.ldflags.outputs.tag }}
    steps:
      - id: checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.3.4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "commit-date=$(git log --date=iso8601-strict -1 --pretty=%ct)" >> "$GITHUB_OUTPUT"
          echo "commit=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --tags --always --dirty | cut -c2-)" >> "$GITHUB_OUTPUT"
          echo "tree-state=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)" >> "$GITHUB_OUTPUT"
          echo "tag=$(git describe --tags --always --dirty)" >> "$GITHUB_OUTPUT"

  # 2nd job - Build application with SLSA that attest to the build process        
  slsa-builder:
    name: slsa-builder-${{matrix.os}}-${{matrix.arch}}
    needs: args
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    strategy:
      matrix:
        os:
          - linux
        arch:
          - amd64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: 1.22
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}}, COMMIT:${{needs.args.outputs.commit}}, VERSION:${{needs.args.outputs.version}}, TREE_STATE:${{needs.args.outputs.tree-state}}"
      config-file: .slsa-goreleaser/${{matrix.os}}-${{matrix.arch}}.yml
      upload-assets: true
  
  sbom:
    permissions:
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
      security-events: write # To upload sarif file with vuln scan results

    name: sbom-${{matrix.os}}-${{matrix.arch}}
    needs: 
      - slsa-builder
      - args
    runs-on: ubuntu-latest

    outputs:
      hashes: ${{ steps.subjects.outputs.hashes }}

    strategy:
      matrix:
        os:
          - linux
        arch:
          - amd64

    steps: 
      - name: Checkout Code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.3.4

      - name: Download Artifact
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: ${{ github.event.repository.name }}_${{needs.args.outputs.version}}-${{matrix.os}}-${{matrix.arch}}

      - name: Create SBOM
        uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751 #v0.16.0 
        with:
          format: spdx-json
          artifact-name: ${{ github.event.repository.name }}_${{needs.args.outputs.version}}-${{matrix.os}}-${{matrix.arch}}-sbom.spdx.json
          output-file: ${{ github.event.repository.name }}_${{needs.args.outputs.version}}-${{matrix.os}}-${{matrix.arch}}-sbom.spdx.json

      - name: 
        id: scan
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a #v3.6.4
        with:
          sbom: ${{ github.event.repository.name }}_${{needs.args.outputs.version}}-${{matrix.os}}-${{matrix.arch}}-sbom.spdx.json
          fail-build: true
          severity-cutoff: critical

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@9fdb3e49720b44c48891d036bb502feb25684276 # v3.25.6
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Generate Checksum
        run: |
          for file in ${{ github.event.repository.name }}*; do
            sha256sum "$file" >> checksum.txt
          done
          cat checksum.txt

      - name: Upload Checksum
        uses: softprops/action-gh-release@0a76e4214a22dfa2946790a0b56e12720488e0d2 #v2.0.5
        with:
          files: |
            checksum.txt

      - name: Generate subjects
        id: subjects
        run: |
          hashes=$(cat checksum.txt | base64 -w0)
          echo "hashes=$hashes" >> $GITHUB_OUTPUT
  
  provenance:
    strategy:
      matrix:
        os:
          - linux
        arch:
          - amd64
    needs: 
      - args
      - sbom
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.sbom.outputs.hashes }}"
      upload-assets: true # do not upload to a new release as we are working in the new release
      upload-tag-name: ${{needs.args.outputs.tag}}
